name: Create PR 

on:
  push: 
  workflow_dispatch:

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: modify file
      run: |
        echo "version bump" >> pyproject.toml
        
    - name: Commit and push pyproject.toml version bump
      uses: EndBug/add-and-commit@v7
      with:
        add: 'pyproject.toml'
        branch: version-bump
        message: 'Committing pyproject.toml version bump'
        push: true
    
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        source_branch: version-bump 
        destination_branch: "main"
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pr_title: "Bump version ${{ github.ref }}" # Title of pull request
        pr_label: "version-bump"                           # Comma-separated list (no spaces)
        pr_allow_empty: false                              # Creates pull request even if there are no changes


